project/accounts/urls.py
from django.conf.urls import url
from. import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

urlpatterns = [

    url(r'^login/$',login,{'template_name':'accounts/login.html'},name="login"),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'},name="logout"),
    url(r'^register/$',views.register,name="register"),
    url(r'^profile/$',views.view_profile,name="view_profile"),
    url(r'^profile/(?P<pk>\d+)/$',views.view_profile,name="view_profile_with_pk"),
    url(r'^profile/edit/$',views.edit_profile, name="edit_profile"),
    url(r'^change-password/$',views.change_password, name="change_password"),

    url(r'^reset-password/$',password_reset,{'template_name':'accounts/reset_password.html',
        'post_reset_redirect':'accounts:password_reset_done','email_template_name':'accounts/reset_password_email.html'},
        name="reset_password"),

    url(r'^reset-password/done/$',password_reset_done,{'template_name':'accounts/reset_password_done.html'}, name="password_reset_done"),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'accounts/reset_password_confirm.html',
         'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),


    url(r'^reset-password/complete/$', password_reset_complete,
        {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')

]

project/home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views

urlpatterns =[
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friends, name='change_friends')

]

project/project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from project import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$',views.login_redirect,name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager,self).get_queryset().filter(city='mumbai')



class UserProfile(models.Model):
    user=models.OneToOneField(User)
    description=models.CharField(max_length=100,default=" ")
    city=models.CharField(max_length=100, default=" ")
    website=models.URLField(default=" ")
    phone=models.IntegerField(default=0)
    image=models.ImageField(upload_to='profile_image',blank=True)

    mumbai=UserProfileManager()

    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        userprofile=UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)

project/home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    post=models.CharField(max_length=250)
    user=models.ForeignKey(User)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

class Friend(models.Model):
    users=models.ManyToManyField(User)
    current_user=models.ForeignKey(User,related_name='owner',null=True)

    @classmethod
    def make_friend(cls,current_user,new_friend):
        friend,created=cls.objects.get_or_create(
            current_user=current_user

        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user

        )
        friend.users.remove(new_friend)

project/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm


class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)

    class Meta:
        model=User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
     )
    def save(self,commit=True):
        user=super(RegistrationForm,self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']

        if commit:
            user.save()
        return user

class EditProfile(UserChangeForm):
    class Meta:
        model=User
        fields=(
            'email',
            'first_name',
            'last_name',
            'password'

        )

project/home/forms.py
from django import forms
from home.models import Post


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))

    class Meta:
        model= Post
        fields = ('post',)

project/accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import RegistrationForm,EditProfile
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.models import User
# Create your views here.


def register(request):
    if request.method == 'POST':
        form=RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))
    else:
        form=RegistrationForm()
        args={'form': form}
        return render(request,'accounts/reg_form.html',args)

def view_profile(request,pk=None):
    if pk:
        user=User.objects.get(pk=pk)
    else:
        user=request.user
    args={'user':user}
    return render(request,'accounts/profile.html',args)


def edit_profile(request):
    if request.method=='POST':
        form=EditProfile(request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:profile'))
    else:
        form=EditProfile(instance=request.user)
        args={'form':form}
        return render(request,'accounts/edit_profile.html',args)


def change_password(request):
    if request.method=='POST':
        form=PasswordChangeForm(data=request.POST,user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect(reverse('accounts:profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form=PasswordChangeForm(user=request.user)
        args={'form':form}
        return render(request,'accounts/change_password.html',args)

project/home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render,redirect
from home.forms import HomeForm
from home.models import Post
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from home.models import Friend


class HomeView(TemplateView):
    template_name ='home/home.html'


    def get(self,request):
        form=HomeForm()
        posts=Post.objects.all().order_by('-created')
        users=User.objects.exclude(id=request.user.id)
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()

        args = {
            'form': form, 'posts': posts, 'users': users, 'friends': friends
        }
        return render(request,self.template_name,args)

    def post(self,request):
        form=HomeForm(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.user=request.user
            post.save()
            text = form.cleaned_data['post']
            form = HomeForm()
            return redirect('home:home')

        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)

def change_friends(request, operation, pk):
        friend = User.objects.get(pk=pk)
        if operation == 'add':
            Friend.make_friend(request.user, friend)
        elif operation == 'remove':
            Friend.lose_friend(request.user, friend)

        return redirect('home:home')

project/project/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

project/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head%}
<title>EditProfile</title>
{% endblock%}

{% block body%}
   <div class="container">
       <h1>Edit Profile</h1>
       <form method="POST">
           {% csrf_token %}
           {{form.as_p}}
            <button class="btn btn-default" type=submit">Submit</button>


       </form>

   </div>
{%endblock %}

project/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head%}
<title>EditProfile</title>
{% endblock%}

{% block body%}
   <div class="container">
       <h1>Edit Profile</h1>
       <form method="POST">
           {% csrf_token %}
           {{form.as_p}}
            <button class="btn btn-default" type=submit">Submit</button>


       </form>

   </div>
{%endblock %}

project/accounts/templates/accounts/home.html
{% extends 'base.html' %}

{% block head%}
<title>Home</title>
{% endblock%}

{% block body%}
    <h1>hello!!!</h1>
{%endblock %}

project/accounts/templates/accounts/login.html
{% extends 'base.html'%}

{% block head %}
<title>Login</title>

{% endblock %}

{% block body%}
<div class="container" >
 <h1>Welcome!!</h1>
 <h2>You can login here:</h2>
 <form method="post">
     {% csrf_token %}
     {{form.as_p}}
     <button class="btn btn-default" type=submit">Login</button>
 </form>


</div>

{% endblock %}

project/accounts/templates/accounts/logout.html
{% extends 'base.html'%}

{% block head %}
<title>Logout</title>

{% endblock %}

{% block body%}
<div class="container" >
 <h1>Logged out</h1>
 <h2>You have logged out</h2>


</div>

{% endblock %}

project/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head%}
<title>Profile</title>
{% endblock%}

{% block body%}
   <div class="container">
       <h1>Profile</h1>
       <p>Username :{{user}}</p>
       <p>First name : {{user.first_name}}</p>
       <p>Last name : {{user.last_name}}</p>
       <p> Email : {{user.email}}</p>
       <p>Description : {{user.userprofile.description}}</p>
       <p>City : {{user.userprofile.city}}</p>
       <p>Phone : {{user.userprofile.phone}}</p>
       <p>Website : {{user.userprofile.website}}</p>
       {% if user.userprofile.image %}
       <img src="{{user.userprofile.image.url}}"  width="300">
       {% endif %}

   </div>
{%endblock %}

project/accounts/templates/accounts/reg_form.html
{% extends 'base.html'%}

{% block body %}
<div class="container">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
      <button class="btn btn-default" type=submit">Submit</button>
</form>
</div>
{% endblock %}

project/accounts/templates/accounts/reset_password.html
{% extends 'base.html'%}

{% block head %}
<title>Reset-password</title>

{% endblock %}

{% block body%}
<div class="container" >
 <h3>Password reset</h3>
 <h4>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</h4>
 <form method="post">
     {% csrf_token %}
     {{form.as_p}}
     <button class="btn btn-default" type=submit">Reset Password</button>
 </form>


</div>

{% endblock %}

project/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

project/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html'%}

{% block head %}
<title>Reset-password-confirm</title>

{% endblock %}

{% block body%}
<div class="container" >
 <h3>Enter new password</h3>
 <h4>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</h4>
 <form method="post">
     {% csrf_token %}
     {{form.as_p}}
     <button class="btn btn-default" type=submit">Reset Password</button>
 </form>


</div>

{% endblock %}

project/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html'%}

{% block head %}
<title>Reset-password_done</title>

{% endblock %}

{% block body%}
<div class="container" >
 <h3>Password reset sent </h3>
 <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>



</div>

{% endblock %}

project/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

project/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
   -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{%static 'accounts/style.css' %}" type="text/css">
     <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    <title>Base</title>
    {%endblock%}
</head>
<body>
 <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Social Network</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif %}
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
        {% block body %}
            <h1>Base</h1>
        {% endblock %}
</body>
 <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

project/home/templates/home/home.html
{% extends 'base.html'%}

{%block body%}
<div class="container">
 <div class="col-md-8">
        <h2>Home</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.post }}
            <br>
            <button type="submit">Submit</button>
        </form>
        <h2>{{ text }}</h2>
        {% for post in posts %}
            <h3>{{ post.post }}</h3>
            <p>Posted by {{ post.user.get_full_name }} on {{ post.created }}</p>
        {% endfor %}
</div>

     <div class="col-md-4">
        <h2>Other People</h2>
        {% for user in users %}
            <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                <h3>{{ user.username }}</h3>
            </a>
         {% if not user in friends %}
            <a href="{% url 'home:change_friends' operation='add' pk=user.pk %}">
            <button type="button" class="btn btn-success">Add Friend</button>
            </a>
         {% endif %}
        {% endfor %}

</div>
      <div class="col-md-4">
        <h2>Friends</h2>
        {% for friend in friends %}
            <a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}">
                <h3>{{ friend.username }}</h3>
            </a>
           <a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}">
            <button type="button" class="btn btn-default">Remove Friend</button>
            </a>
        {% endfor %}

</div>
</div>


{% endblock %}